### ISSUE TITLE
v2 labels do not work side by side with v1 labels.

### ISSUE THREAD

**Issue by tony-gamble-asos** [microsoft/service-fabric-traefik#11]
Sample configuration of service labels for traefik V1 

```
<Extensions>
            <Extension Name="Traefik">
                <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
                    <Label Key="traefik.enable">true</Label>
                    <Label Key="traefik.frontend.passHostHeader">true</Label>
                    <Label Key="traefik.frontend.rule">PathPrefix: /weatherforecast</Label>
                    <Label Key="traefik.backend.healthcheck.path">/healthcheck</Label>
                </Labels>
            </Extension>
  </Extensions>
```

To allow for the seamless transition of V1 to V2 it would be helpful if both sets of labels could be supported side by side. 

Currently any service with the above v1 configuration causes the fetcher application to crash . (Related to https://github.com/microsoft/service-fabric-traefik/issues/10)

**Comment by egaribay77** [comment]
This should now be fixed with v1.0.0 release (https://github.com/microsoft/service-fabric-traefik/pull/17).
