### ISSUE TITLE
Random 404 errors in traffic routing

### ISSUE THREAD

**Issue by nokjuh** [microsoft/service-fabric-traefik#25]
When there are lots of requests going to a Service Fabric cluster, some of them will fail to 404 error. This varies how often it happens, between about 1 to 30 minutes between errors. Then there will be a period of a few seconds where some requests fail to 404 errors. These errors happen often enough that the Service Fabric plugin cannot be used in heavy production use. These errors did not happen with Traefik 1.7.

Based on analyzing the Traefik and Service Fabric plugin logs, this is caused by the Service Fabric dynamic configuration sometimes being read by Traefik as completely empty on one Service Fabric node's Traefik, then returning to normal a few seconds later the next time Traefik reads the configuration. Based on discussions with Traefik support, this seems to be caused by specific timing when reading the Service Fabric configuration, so that the configuration file is either missing or empty just as it's being read.

It seems that this is likely caused by the configuration file handling but I don't know it could be fixed.
https://github.com/microsoft/service-fabric-traefik/blob/488ce82ce9151d86e6b39bd34381841345097bf8/src/serviceFabricDiscoveryService/pkg/discovery/discoveryservice.go#L96
err := os.WriteFile(disco.publishFilePath, data, 0644)

The Traefik logs will show something like:
...00:00:05Z" level=debug msg="Skipping unchanged configuration." providerName=file
...00:00:08Z" level=debug msg="Configuration received: <no backends>
...00:00:10Z" level=debug msg="Configuration received: <all backends>
...00:00:12Z" msg="Skipping unchanged configuration." providerName=file

Service Fabric plugin debug logs will show:
...00:00:03Z" level=debug msg="New snapshot arrived: <all backends>
...00:00:08Z" level=debug msg="New snapshot arrived: <all backends>
...00:00:13Z" level=debug msg="New snapshot arrived: <all backends>

Most likely the Service Fabric plugin is writing new configuration at 00:00:08 at some exact timing when Traefik is reading the configuration file, and Traefik gets empty or missing file.

Service Fabric plugin is configured to write the configuration (PUBLISH_FILE_PATH) to "..\work\sf_discovered.yaml" and Traefik is configured to read the directory (which has also traefik_dynamic.toml with other settings):
[providers]
  [providers.file]
     directory = "../work"
            watch = true

This is currently preventing us from taking Traefik 2.x into use with Service Fabric.

**Comment by Mahons** [comment]
Hi @nokjuh, We're due to bring Traefik 2.x into production later this month. We haven't experienced the above issue during our performance testing, but I'm wondering how much "lots of requests" means for you? The above is making me even more nervous of upgrading.

**Comment by Mahons** [comment]
Thanks for the quick response, @nokjuh. I 100% agree with your last statement; that's not something I would approve of internally. 

In saying that, we fortunately already have retries built into our service calls (using Polly), and perhaps that's why we've yet to see it during our integration or performance tests. We'll have to review our logs to see if it's an issue that's been hidden from us until now.

**Comment by Mahons** [comment]
Hi @nokjuh, 

We've been carrying out further Performance Tests in a dedicated environment (Previous tests performed were local to our dev environment). Like you, we've encountered ongoing issues with services not being found. Traefik Support has been brilliant in helping me investigate the problem, but we're still looking for a solution. I've now recommended that we don't upgrade to V2 of Traefik until these issues with the integration are resolved. 

I will note that our log files don't show the same issue as described above, i.e., empty configuration (we always appear to get a configuration; however, Traefik gives out that it can't always find a service, which leads me to believe that the configuration is not loading or there is a small window between the service configuration loading/reloading.

Best,

Stephen

@craftyhouse @dariopb Is this something you can assist with?

**Comment by nokjuh** [comment]
This should be fixed with pull requests #29 , #30 , and #31 . Each fixes a different case which can lead to Traefik reading a missing, empty, or practically empty configuration.

**Comment by egaribay77** [comment]
fixed with pull requests #29  , #30  , and #31
