### ISSUE TITLE
Traefik returning 404 while cluster is performing rolling upgrade

### ISSUE THREAD

**Issue by TF-Tyler** [microsoft/service-fabric-traefik#4]
Good afternoon @craftyhouse ,

Two questions in regards to this, and I apologize if this is in the wrong place to bring this up.

**Background**: _An issue we are experiencing with using traefik (legacy has traefik running in a docker container on the sf cluster) and not necessarily the repo in question. The issue is when SF upgrades and a node goes down, services that are being communicated with through traefik are being migrated to another node and no longer on the node with traefik. Traefik on that node then receives a request for the service in question and returns a 404 since traefik on that node doesn't have an application of that instance._

**Questions**
1. Do you know if this new repo would address this issue? I'm assuming it would potentially address this issue by being aware that the sf cluster is currently shutting down the node in question and handle it in some given way.
2. Do you know if this scenario would persist when this reverse proxy solution eventually gets implemented, or would it be handled gracefully by the cluster and the built in reverse proxy.

**Comment by craftyhouse** [comment]
@dario-ms

**Comment by esbenbach** [comment]
On that note: Will this package support request draining the way the existing RP does?

**Comment by egaribay77** [comment]
Should be fixed by 
https://github.com/microsoft/service-fabric-traefik/pull/29
https://github.com/microsoft/service-fabric-traefik/pull/30
https://github.com/microsoft/service-fabric-traefik/pull/31
