### ISSUE TITLE
Loadbalancer labels not being picked up.

### ISSUE THREAD

**Issue by tony-gamble-asos** [microsoft/service-fabric-traefik#9]
Label configuration :

      <Extensions>
        <Extension Name="Traefik">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="traefik.http.PingerEndpoint0">true</Label>
            <Label Key="traefik.http.PingerEndpoint0.router.entrypoints">websecure</Label>
            <Label Key="traefik.http.PingerEndpoint0.router.rule">PathPrefix(`/weatherforecast`)</Label>
            <Label Key="traefik.http.PingerEndpoint0.loadbalancer.passhostheader">true</Label>
            <Label Key="traefik.http.PingerEndpoint0.loadbalancer.healthcheck.path">/weatherforecast</Label>
            <Label Key="traefik.http.PingerEndpoint0.loadbalancer.healthcheck.interval">10s</Label>
            <Label Key="traefik.http.PingerEndpoint0.loadbalancer.healthcheck.scheme">https</Label>
          </Labels>
        </Extension>
      </Extensions>
     
Fetcher Out put :

    fabric-Application3-Web1-http-PingerEndpoint0-317677a7-7d03-4406-8d36-929eb6658f8b:
      loadBalancer:
        passHostHeader: null
        servers:
        - Port: ""
          Scheme: ""
          url: http://ASAZ-XXXXXXXX:9022

None of the load balancer values are written to the traefik configuration file

**Comment by egaribay77** [comment]
Hello, thank you for reaching out. 

This is an issue with documentation.  For load balancer labels need to add ".service." between endPointName and loadbalancer. Also, the current implementation parses the rules differently from the Traefik plugin code. More details here: https://github.com/dariopb/traefikServiceFabricPlugin/issues/10#issuecomment-965612764. The implementation can found in the repo under src/serviceFabricDiscoveryService/pkg/discovery

Example:
  <Extensions>
	  <Extension Name="Traefik">
		  <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
			  <Label Key="traefik.http.WeatherForecastEndpoint0">true</Label>
			  <Label Key="traefik.http.WeatherForecastEndpoint0.router.entrypoints">websecure</Label>
			  <Label Key="traefik.http.WeatherForecast0.router.rule">PathPrefix(`/weatherforecast`)</Label>
			  <Label Key="traefik.http.WeatherForecastEndpoint0.middlewares.1.stripPrefix.prefixes">"/weatherforecast</Label>
			  <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.passhostheader">true</Label>
			  <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.healthcheck.path">/weatherforecast</Label>
			  <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.healthcheck.interval">10s</Label>
			  <Label Key="traefik.http.WeatherForecastrEndpoint0.service.loadbalancer.healthcheck.scheme">https</Label>
			  <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.name">stickycookie</Label>
                                   <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.secure">true</Label>
                                   <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.httpOnly">true</Label>
                                   <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.sameSite">none</Label>
		  </Labels>
	  </Extension>
  </Extensions>


Fetcher Output (loadbalancer section):
  services:
    fabric-TestSFApp-WeatherForecastServicePkg-http-WeatherForecastEndpoint0:
      loadBalancer:
        healthCheck:
          followRedirects: null
          interval: 10s
          path: /weatherforecast
          scheme: https
        passHostHeader: true
        servers:
        - Port: ""
          Scheme: ""
          url: http://desktop-xxxxxxxx:8387/
        sticky:
          cookie:
            httpOnly: true
            name: stickycookie
            sameSite: none
            secure: true
